#
# Makefile for ifgi/cpp/api
# Copyright (C) 2010-2011 Yamauchi, Hitoshi
#

# root directory of ifgi-path-tracer
IFGI_ROOT := ../../..

#
# common setup/defines
#
include $(IFGI_ROOT)/tool/Premake.mk

#----------------------------------------------------------------------
# each Makefile define
#----------------------------------------------------------------------
# sub directories
SUBDIR :=


# additional clean files
ADDITIONAL_CLEAN_FILE := ifgi_cpp_render_mod.so



#----------------------------------------------------------------------
#
# setup depends on each Makefile and TARGET
#
include $(IFGI_ROOT)/tool/Postmake.mk
